mkdir: cannot create directory ‘/eos/home-s/spalluot/www/MTD/MTDTB_CERN_Sep23/ModuleCharacterization/HPK_nonIrr_LYSO813_Vov2.00_angle52_T5C/summaryPlots/’: File exists
mkdir: cannot create directory ‘/eos/home-s/spalluot/www/MTD/MTDTB_CERN_Sep23/ModuleCharacterization/HPK_nonIrr_LYSO813_Vov2.00_angle52_T5C/summaryPlots/tot/’: File exists
mkdir: cannot create directory ‘/eos/home-s/spalluot/www/MTD/MTDTB_CERN_Sep23/ModuleCharacterization/HPK_nonIrr_LYSO813_Vov2.00_angle52_T5C/summaryPlots/energy/’: File exists
mkdir: cannot create directory ‘/eos/home-s/spalluot/www/MTD/MTDTB_CERN_Sep23/ModuleCharacterization/HPK_nonIrr_LYSO813_Vov2.00_angle52_T5C/summaryPlots/timeResolution/’: File exists
mkdir: cannot create directory ‘/eos/home-s/spalluot/www/MTD/MTDTB_CERN_Sep23/ModuleCharacterization/HPK_nonIrr_LYSO813_Vov2.00_angle52_T5C/summaryPlots/timeResolution/fit/’: File exists
Traceback (most recent call last):
  File "moduleCharacterizationSummaryPlots.py", line 705, in <module>
    g_tot_vs_bar[l, vov, thRef].Sort()
KeyError: ('L', 2.0, 11)
